apiVersion: v1
kind: Namespace
metadata:
  name: <NAMESPACE_NAME>
spec: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: <DEPLOYMENT_NAME>
  name: <DEPLOYMENT_NAME>
  namespace: <NAMESPACE_NAME>
spec:
  replicas: 3
  selector:
    matchLabels:
      app: <DEPLOYMENT_NAME>
  strategy: {}
  template:
    metadata:
      labels:
        app: <DEPLOYMENT_NAME>
    spec:
      containers:
      - image: <IMAGE_NAME>
        name: <DEPLOYMENT_NAME>
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: BACKEND_HOST
          value: "backend.<NAMESPACE_NAME>.svc.cluster.local"
        - name: MESSAGE
          value: "hvorfor leser du meldingene mine"
        resources:
          limits:
            cpu: 30m
            memory: 96Mi
          requests:
            cpu: 30m
            memory: 96Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: <DEPLOYMENT_NAME>
  name: <DEPLOYMENT_NAME>
  namespace: <NAMESPACE_NAME>
spec:
  replicas: 3
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: <DEPLOYMENT_NAME>
  env:
  - name: MESSAGE
    value: "ny melding"
  type: NodePort
status:
  loadBalancer: {}
