apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: <DEPLOYMENT_NAME>
  name: <DEPLOYMENT_NAME>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <DEPLOYMENT_NAME>
  strategy: {}
  template:
    metadata:
      labels:
        app: <DEPLOYMENT_NAME>
    spec:
      containers:
      - image: <IMAGE_NAME>
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: <DEPLOYMENT_NAME>
  name: <DEPLOYMENT_NAME>
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: <DEPLOYMENT_NAME>
  type: LoadBalancer
