services:
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    links:
      - backend

  backend:
    build: backend
    environment:
      - MESSAGE=Hei_Ellen
    ports:
      - "8080:8080"
