services:
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    links:
      - backend

  backend:
    build: backend
# fjern
    ports:
      - "8080:8080"
#   environment:
#     - MESSAGE=Hello from Docker
