apiVersion: v1
kind: Namespace
metadata:
  name: <NAMESPACE_NAME>
spec: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: <DEPLOYMENT_NAME>
  name: <DEPLOYMENT_NAME>
  namespace: <NAMESPACE_NAME>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <DEPLOYMENT_NAME>
  strategy: {}
  template:
    metadata:
      labels:
        app: <DEPLOYMENT_NAME>
    spec:
      containers:
      - image: <IMAGE_NAME>
        name: <DEPLOYMENT_NAME>
        ports:
        - containerPort: 8080
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MESSAGE
          value: "Hei på deg"
        resources:
          limits:
            cpu: 30m
            memory: 32Mi
          requests:
            cpu: 30m
            memory: 32Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: <DEPLOYMENT_NAME>
  name: <DEPLOYMENT_NAME>
  namespace: <NAMESPACE_NAME>
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: <DEPLOYMENT_NAME>
  type: NodePort
status:
  loadBalancer: {}
