name: Build and Deploy

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: 'Build Docker image and push to registry'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: 'ghcr.io'
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image to registry
        uses: docker/build-push-action@v5
        with:
          push: 'true'
          tags: 'ghcr.io/${{ github.repository }}/${{ github.head_ref }}:latest'
          context: 'frontend'

  deploy:
    name: 'Deploy to Kubernetes'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubeconfig
        run: |
          cat <<EOF > ~/.kube/config
          ${{ secrets.KUBE_CONFIG }}
          EOF

      - name: Run kubectl apply
        run: |
          sed -i 's|<IMAGE_NAME>|ghcr.io/${{ github.repository }}/${{ github.head_ref }}:latest|g' deployment.yml
          sed -i 's|<DEPLOYMENT_NAME>|${{ github.head_ref }}|g' deployment.yml

          kubectl apply -f deployment.yml
